### PR TITLE
Add zh_CN Translate

### PR DESCRIPTION
**Pull request by ItsDApples**
Hello, im really like your troll plugin. its very funny!

i made a simplified chinese translate for it(ps: idk how your lang system work so may cause error)

btw, can i repost this plugin to minebbs.com(a large minecraft forum in china)? it can help more chinese player know this fun 

plugin, ill direct the origin link for download and the author. and on my testing of plugin in 1.21 it output some errors 

you can check it at https://paste.helpch.at/nutahodusi.php

### CODE REVIEW

**Comment by DxsSucuk** [comment]
Thank you very much for the translation!
I noticed a few Issues with it thou, you replaced the word "The" in other translations by accident.
And for the Issue you are having to fix that install ProtocolLib.

**Comment by ItsDApples** [comment]
Oh, sry ill fix it.

**Comment by ItsDApples** [comment]
Fixed. you can check it
btw what about the repost? 
i wont redistribute your plugin and just write some plugin information on it. if user click the download button, they will direct your published websites :3

**Comment by DxsSucuk** [comment]
I have merged your translation with the new system! So Imma close this merge, and for your question sure! But please note to the users of that website that you are not the developer and that I am in no relation with that posting.

**Pull request closed without merging**
